# Settings for ros_control hardware interface
hardware_interface:
   joints:
      - lwheel
      - rwheel

# Publish all joint states by pusblishing on /joint_states topic necessary in ROS
joint_state_controller:
   type: joint_state_controller/JointStateController
   publish_rate: 5

# Choose the controller type you need to use
joint_group_position_controller:
   type: position_controllers/JointGroupPositionController
   joints:
      - lwheel
      - rwheel

